name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration_test:
    name: Run Integration Test
    runs-on: macos-latest
    strategy:
      matrix: 
        device:
          - "pixel"
          - "pixel_xl"
          - "pixel_c"
          - "Nexus 6"

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get
      
      - name: Start Android Emulator and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: x86_64
          profile: ${{ matrix.device }}
          script: flutter test integration_test/app_test.dart